{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"planets.py: A homework to roughly modify the movements of the planets.\n",
    "\n",
    "__author__ = \"胡奕潇\"\n",
    "__pkuid__  = \"1700011716\"\n",
    "__email__  = \"1700011716@pku.edu.cn\"\n",
    "\"\"\"\n",
    "\n",
    "import math\n",
    "import turtle\n",
    "\n",
    "def start(name,q):\n",
    "    name.up()\n",
    "    name.speed(\"fast\")\n",
    "    name.goto(2/3*q,0)\n",
    "    name.down()\n",
    "    name.shape(\"circle\")\n",
    "\n",
    "def move(name,e,p,sp):\n",
    "    ang=an*(math.pi/180)\n",
    "    t=e*p/(1-e*math.cos(ang*sp))\n",
    "    x=t*math.cos(ang*sp)\n",
    "    y=t*math.sin(ang*sp)\n",
    "    name.goto(x,y)\n",
    "\n",
    "    \n",
    "def main():\n",
    "    turtle.color(\"red\")\n",
    "    turtle.shape(\"circle\")\n",
    "    turtle.up()\n",
    "    \n",
    "    sc=turtle.Screen()\n",
    "    sc.bgcolor(\"darkblue\")\n",
    "    \n",
    "    alice=turtle.Turtle()\n",
    "    alice.color(\"aliceblue\")\n",
    "    bob=turtle.Turtle()\n",
    "    bob.color(\"blanchedalmond\")\n",
    "    cindy=turtle.Turtle()\n",
    "    cindy.color(\"yellow\")\n",
    "    dave=turtle.Turtle()\n",
    "    dave.color(\"lightpink\")\n",
    "    eve=turtle.Turtle()\n",
    "    eve.color(\"lawngreen\")\n",
    "    fiona=turtle.Turtle()\n",
    "    fiona.color(\"orange\")\n",
    "\n",
    "    start(alice,120)  \n",
    "    start(bob,67)\n",
    "    start(cindy,270)\n",
    "    start(dave,300)\n",
    "    start(eve,405)\n",
    "    start(fiona,286)\n",
    "    \n",
    "    for an in range(500):\n",
    "        def move(name,e,p,sp):\n",
    "            ang=an*(math.pi/180)\n",
    "            t=e*p/(1-e*math.cos(ang*sp))\n",
    "            x=t*math.cos(ang*sp)\n",
    "            y=t*math.sin(ang*sp)\n",
    "            name.goto(x,y)\n",
    "        move(alice,0.4,120,6)\n",
    "        move(bob,0.2,180,8)\n",
    "        move(cindy,0.6,120,4)\n",
    "        move(dave,0.4,300,3)\n",
    "        move(eve,0.2,1080,2)\n",
    "        move(fiona,0.5,190,3.5)\n",
    "        \n",
    "           \n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()\n",
    "\n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
